### ISSUE TITLE
 Can't load config for 'flexudy/t5-base-multi-sentence-doctor'

### ISSUE THREAD

**Issue by jjtail** [flexudy-pipe/sentence-doctor#2]
Hi,
    I had an error when I loading the model according to usage.
```
     Can't load config for 'flexudy/t5-base-multi-sentence-doctor'. Make sure that:

- 'flexudy/t5-base-multi-sentence-doctor' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'flexudy/t5-base-multi-sentence-doctor' is the correct path to a directory containing a config.json file
```

**Comment by zolekode** [comment]
Hi @jjtail i am sorry for replying this late. For some reason i don't get notified. So I just copy pasted the code found in the documentation into a fresh pycharm project and everything works normally. Do you still have the problem?
Which version of transformers are you using ?

**Comment by katreparitosh** [comment]
Hi @zolekode,

While I was deploying a transformer-based saved model using docker, I also received the same error during inference. 

I am using transformers == 3.3.1. 

Would be great if you had any advice on this. 

Regards,
Paritosh.

**Comment by zolekode** [comment]
Hi @katreparitosh please did you train the sentence-doctor yourself, or did you directly load it from the huggingface hub ?

**Comment by katreparitosh** [comment]
Hi @zolekode,

Well, actually, I have trained a BERT model using fast-bert that implements transformers. The model inferences perfectly when I deploy the flask app on local. 

However, when I docker the entire stuff to deploy on EC2, I receive the above errors when I pass a sentence for inference. 

While searching the stack-trace, I came across this thread.

**Comment by zolekode** [comment]
I am not sure I quite get it @katreparitosh. The Sentence-Doctor is a T5 model (not BERT). 
Could you share the relevant part of the code you use to make inferences ?

**Comment by katreparitosh** [comment]
Hi @zolekode, sorry for the late response.

No, I am not utilizing Sentence-Decoder. 

I trained a BERT model for classification purposes using [fast-bert](https://github.com/kaushaltrivedi/fast-bert). 

When I tried to deploy the saved model on EC2 using docker, I received the exact errors mentioned above regarding "Can't load config........." at the time when I passed a sentence for classification inference. While trying to debug the problem, I came across this thread from GitHub search. 

Hence, I decided to ask if any solution was found for this because inherently the issue stated the same problem.

This is the code where I load the saved model to make an inference (Flask Code).
```
@app.route('/api/text', methods=['POST'])
def upload_text():
    text = request.form['text']
    predictor = BertClassificationPredictor(model_path=LOCAL_MODEL_PATH,
                                            label_path=LOCAL_CSV,  # location for labels.csv file
                                            multi_label=False,
                                            model_type='distilbert',
                                            do_lower_case=False
                                            )
    result = predictor.predict(text)
```
I hope I was clear. 

Let me know if you want more details. Also, thanks for trying to help.

**Comment by zolekode** [comment]
ok @katreparitosh no problem. The error simply means that the path provided is not correct. Please make sure you have access to the right directory. 

If you are using docker, then the path is definitely different from the path on you local computer. To access the correct path of the python file executing your application (for example app.py), use `import os` and get the full path of app.py with `os.getcwd()`..

Now from there you can access the model where ever it is found in the project directory.
Let me know if it solves your problem.

**Comment by katreparitosh** [comment]
Hi @zolekode 

Thanks a lot for your advice. 

I shall try it and let you know soon.
