### ISSUE TITLE
Need clarifications with Model output

### ISSUE THREAD

**Issue by Viveka-S** [flexudy-pipe/sentence-doctor#4]
Hi,
I am using this sentence doctor model with transformer pipeline. I have tested this model with various inputs. I have some questions regarding the outputs. I thought this model corrects the grammar and spelling of the given sentence.

```
print(nlp("repair_sentence:This is supre idea"))
print(nlp("repair_sentence:This is superr idea"))
print(nlp("repair_sentence:This is super"))
```
For the above inputs, I received

[{'generated_text': 'This is a very good idea.'}]
[{'generated_text': 'This is a great idea.'}]
[{'generated_text': 'This is super super cool.'}]

I thought the model will correct the spelling, but generate some extra words. **Was this expected**? Or am I missing something? I also learned this model is trained in three languages - English, french, german. When I gave this sentence,

`print(nlp("repair_sentence:How you say this in english 'Comment ça va'"))`

the output that I got is,
[{'generated_text': "Comment you say this in english 'Comment ça va'."}]

It mixes up the languages. Sometimes if I specify the sentence without giving **repair_sentence:** then the output is much confusing,
`print(nlp("This is my favoriete color"))`
[{'generated_text': '**Cette** is my favorite color.'}]

The word this is converted to cette (french).

`print(nlp("This is super"))`
[{'generated_text': 'Voilà super super super super super super super super cool! This is super super cool!'}]

 **Is there a way to set the language**?

The code I am using is,

```
!pip install transformers
!pip install sentencepiece
from transformers.pipelines import pipeline
nlp = pipeline("text2text-generation", model="flexudy/t5-base-multi-sentence-doctor")
print(nlp("This is super"))
```

And the model was able to process one sentence. **Is there a way to process a paragraph f 4~5 lines**?

I using Google colab.
Happy to hear from you guys. Thanks in advance.

**Comment by zolekode** [comment]
Hello @Viveka-S sorry, I haven't checked the library in a while. Let me take some time to answer your question in detail:

- First, the model is not primarily intended for grammar and spelling correction. The primary purpose of the model is to correct errors that occur during sentence boundary detection. 
- By chance, the model "might attempt" correct grammar if no context sentence is provided.
- Please pay attention to the input format (the T5 model is very sensitive to prompt operators): "repair_sentence: [space] {sentence to repaire} [space] {left context} [space] {right context} \</s>"
- For grammar correction, just pass empty left and right contexts. Please read the documentation attentively. I explained everything in detail there.
- The sentence doctor was only trained on 150K sentences with T5 small which IMO is not too robust (see disclaimer in readme). Train a bigger model with more data to obtain better results.
- At last, T5 typically hallucinates text. I think this is even reported in the paper. That is why if you want a grammar checker or fixer, you must do some post-processing to check whether sporous information wasn't added.

That said, the good news is I will be releasing a true grammar fixer for German, French and English soon on the hugging face hub. Check out flexudy.com/pipe for any possible updates on the subject matter.
